name: Solicitar Funcionalidade
description: Sugira uma nova funcionalidade para esse projeto
title: "[FEATURE]"
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Sua solicitação de funcionalidade está relacionada a um problema? Por favor descreva.**

  - type: textarea
    id: problem-description
    attributes:
      label: Uma descrição clara e concisa de qual é o problema.
      placeholder: Ex. Estou sempre frustrado quando...

  - type: markdown
    attributes:
      value: |
        **Descreva a solução que você deseja**

  - type: textarea
    id: desired-solution
    attributes:
      label: Uma descrição clara e concisa do que você deseja que aconteça.
      placeholder: Descreva a solução desejada aqui.

  - type: markdown
    attributes:
      value: |
        **Descreva as alternativas que você considerou**

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Uma descrição clara e concisa de quaisquer soluções ou recursos alternativos que você considerou ou tentou.
      placeholder: Descreva as alternativas consideradas aqui.

  - type: markdown
    attributes:
      value: |
        **Contexto adicional**

  - type: textarea
    id: additional-context
    attributes:
      label: Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de recurso aqui.
      placeholder: Adicione contexto adicional aqui.
